-- 1. Criação da tabela de Clientes
CREATE TABLE IF NOT EXISTS public.clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  loja_id BIGINT NOT NULL,
  nome TEXT NOT NULL,
  telefone TEXT,
  email TEXT,
  cpf_cnpj TEXT,
  endereco TEXT
);

-- Ativar RLS
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read/write for all users" ON public.clientes FOR ALL USING (true) WITH CHECK (true);

-- 2. Adicionar relação na tabela ordens_servico
-- Ignorar erro caso a coluna ja exista
DO $$
BEGIN
  BEGIN
    ALTER TABLE public.ordens_servico ADD COLUMN cliente_id BIGINT REFERENCES public.clientes(id);
  EXCEPTION
    WHEN duplicate_column THEN RAISE NOTICE 'coluna cliente_id ja existe';
  END;
END $$;
