-- Tabela para controle de estoque de peças
CREATE TABLE IF NOT EXISTS public.pecas_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    categoria TEXT,
    quantidade INTEGER DEFAULT 0,
    minimo_estoque INTEGER DEFAULT 1,
    valor_compra DECIMAL(10,2) DEFAULT 0.00,
    valor_venda DECIMAL(10,2) DEFAULT 0.00,
    loja_id BIGINT REFERENCES public.lojas(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Habilitar RLS
ALTER TABLE public.pecas_estoque ENABLE ROW LEVEL SECURITY;

-- Políticas de segurança
CREATE POLICY "Permitir tudo para usuários da mesma loja" ON public.pecas_estoque
    FOR ALL USING (
        loja_id IN (
            SELECT loja_id FROM public.usuarios WHERE email = auth.email()
        )
    );

-- Tabela para histórico de movimentação (Opcional, mas profissional)
CREATE TABLE IF NOT EXISTS public.movimentacao_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estoque_id BIGINT REFERENCES public.pecas_estoque(id) ON DELETE CASCADE,
    tipo TEXT CHECK (tipo IN ('ENTRADA', 'SAÍDA')),
    quantidade INTEGER NOT NULL,
    motivo TEXT, -- ex: 'Compra', 'Venda', 'Ajuste', 'Ordem de Serviço #123'
    estoque_anterior INTEGER,
    estoque_atual INTEGER,
    usuario_id BIGINT REFERENCES public.usuarios(id),
    loja_id BIGINT REFERENCES public.lojas(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.movimentacao_estoque ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir tudo para movimentação da mesma loja" ON public.movimentacao_estoque
    FOR ALL USING (
        loja_id IN (
            SELECT loja_id FROM public.usuarios WHERE email = auth.email()
        )
    );
