-- ==========================================
-- STORE TECH - ATUALIZAÇÃO COMPLETA DO BANCO
-- Rode este script no SQL Editor do Supabase
-- ==========================================

-- 1. Tabela de Clientes (caso não exista)
CREATE TABLE IF NOT EXISTS public.clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  loja_id BIGINT NOT NULL,
  nome TEXT NOT NULL,
  telefone TEXT,
  email TEXT,
  cpf_cnpj TEXT,
  endereco TEXT
);

ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "clientes_all" ON public.clientes FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- 2. Recriação da tabela ordens_servico com TODOS os campos profissionais
-- Primeiro, dropar a antiga se existir (CUIDADO: apaga dados existentes)
-- Se você já tem dados, comente o DROP e use os ALTERs individuais abaixo
DROP TABLE IF EXISTS public.ordens_servico;

CREATE TABLE public.ordens_servico (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  loja_id BIGINT NOT NULL,
  user_id BIGINT,
  tecnico_id BIGINT,
  cliente_id BIGINT REFERENCES public.clientes(id),

  -- DADOS DO CLIENTE (desnormalizados para impressão rápida)
  cliente_nome TEXT NOT NULL,
  cliente_telefone TEXT,

  -- DADOS DO APARELHO
  marca TEXT,
  modelo TEXT NOT NULL,
  cor TEXT,
  imei TEXT,
  senha TEXT,
  aparelho_liga BOOLEAN DEFAULT true,

  -- CHECKLIST DE ENTRADA (estado físico)
  checklist_tela TEXT DEFAULT 'OK',
  checklist_traseira TEXT DEFAULT 'OK',
  checklist_carcaca TEXT DEFAULT 'OK',
  checklist_botoes TEXT DEFAULT 'OK',
  checklist_cameras TEXT DEFAULT 'OK',
  checklist_som TEXT DEFAULT 'OK',
  checklist_carregamento TEXT DEFAULT 'OK',
  checklist_wifi TEXT DEFAULT 'OK',
  checklist_biometria TEXT DEFAULT 'OK',

  -- ACESSÓRIOS ENTREGUES
  acessorio_chip BOOLEAN DEFAULT false,
  acessorio_cartao_memoria BOOLEAN DEFAULT false,
  acessorio_carregador BOOLEAN DEFAULT false,
  acessorio_capinha BOOLEAN DEFAULT false,
  acessorio_pelicula BOOLEAN DEFAULT false,
  acessorio_outros TEXT,

  -- SERVIÇO
  defeito_relatado TEXT,
  laudo_tecnico TEXT,
  servico_realizado TEXT,
  pecas_utilizadas TEXT,
  observacoes TEXT,

  -- FINANCEIRO E PRAZOS
  valor_orcamento NUMERIC DEFAULT 0,
  valor_pecas NUMERIC DEFAULT 0,
  valor_mao_obra NUMERIC DEFAULT 0,
  forma_pagamento TEXT,
  data_entrada TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  data_previsao TIMESTAMP WITH TIME ZONE,
  data_entrega TIMESTAMP WITH TIME ZONE,

  -- GARANTIA
  garantia_dias INTEGER DEFAULT 90,
  termo_garantia TEXT DEFAULT 'Garantia válida para o serviço realizado. Não cobre: mau uso, quedas, umidade/oxidação, violação de lacres por terceiros.',

  -- CONTROLE
  status TEXT DEFAULT 'Entrada' NOT NULL,
  prioridade TEXT DEFAULT 'Normal',
  registrado_conserto BOOLEAN DEFAULT false
);

ALTER TABLE public.ordens_servico ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "os_all" ON public.ordens_servico FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
